# Generated by Django 3.2.9 on 2021-12-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_websiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=60, null=True),
        ),
    ]
