# Generated by Django 3.2.9 on 2021-12-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_websiteApp', '0002_film_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
